name: dart_discord_bot
description: Discord bot using public API
version: 1.0.0

environment:
  sdk: ^3.4.4

dependencies:
  # path: ^1.8.0
    nyxx: ^5.1.1
    #flutter:
     # sdk: flutter
    sqlite3: ^2.4.4
    #sqlite3_flutter_libs: ^0.5.24
    ffi: ^2.1.2
    http: ^0.13.3
    dotenv: ^4.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
